apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Python flask application that displays time, named ${{ values.app_name }}
    # Example for optional annotations
  annotations:
     github.com/project-slug: mosesadelere/${{ values.app_name }}
spec:
  type: service
  owner: developers
  lifecycle: experimental